'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams, useRouter } from 'next/navigation';
import { api, clearToken } from '@/lib/api';

type Tab = 'announcements' | 'members' | 'donations' | 'settings';
interface Mosque { name: string; address?: string; phone?: string; email?: string; timezone: string; brand_color: string }
interface Announcement { announcement_id: number; title: string; content: string; category: string; posted_at: string }
interface Membership { membership_id: number; role: string; status: string; user: { name: string; email: string } }
interface Donation { donation_id: number; receipt_number: string; amount: number; currency: string; category: string; reconciliation_status: string }

export default function AdminDashboard() {
  const params = useParams(); const router = useRouter(); const slug = typeof params?.slug === 'string' ? params.slug : 'al-noor';
  const [tab, setTab] = useState<Tab>('announcements'); const [mosque, setMosque] = useState<Mosque | null>(null); const [announcements, setAnnouncements] = useState<Announcement[]>([]); const [members, setMembers] = useState<Membership[]>([]); const [donations, setDonations] = useState<Donation[]>([]); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [category, setCategory] = useState('General');
  const [invite, setInvite] = useState({ name: '', email: '', role: 'member', temporary_password: '' });

  async function load() {
    setError('');
    try { const [m,a,ms,ds] = await Promise.all([api<Mosque>(null, `/api/mosques/${slug}`), api<Announcement[]>(slug, '/api/announcements'), api<Membership[]>(slug, '/api/admin/memberships'), api<Donation[]>(slug, '/api/admin/donations')]); setMosque(m); setAnnouncements(a); setMembers(ms); setDonations(ds); }
    catch (e) { setError(e instanceof Error ? e.message : 'Workspace could not be loaded.'); }
  }
  useEffect(() => { load(); }, [slug]);
  function done(text: string) { setMessage(text); setError(''); setTimeout(() => setMessage(''), 3000); }

  async function publish(e: FormEvent) { e.preventDefault(); try { await api(slug, '/api/admin/announcements', { method: 'POST', body: JSON.stringify({ title, content, category, status: 'Published', audience: 'Public' }) }); setTitle(''); setContent(''); done('Announcement published.'); load(); } catch (x) { setError(x instanceof Error ? x.message : 'Could not publish.'); } }
  async function inviteMember(e: FormEvent) { e.preventDefault(); try { await api(slug, '/api/admin/memberships/invite', { method: 'POST', body: JSON.stringify(invite) }); setInvite({ name: '', email: '', role: 'member', temporary_password: '' }); done('Member added.'); load(); } catch (x) { setError(x instanceof Error ? x.message : 'Could not add member.'); } }
  async function saveSettings(e: FormEvent) { e.preventDefault(); try { setMosque(await api<Mosque>(slug, `/api/mosques/${slug}`, { method: 'PUT', body: JSON.stringify(mosque) })); done('Mosque settings saved.'); } catch (x) { setError(x instanceof Error ? x.message : 'Could not save settings.'); } }
  async function exportDonations() { try { const csv = await api<string>(slug, '/api/admin/donations/export.csv'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); const link = document.createElement('a'); link.href = url; link.download = `${slug}-donations.csv`; link.click(); URL.revokeObjectURL(url); done('Donation report exported.'); } catch (x) { setError(x instanceof Error ? x.message : 'Could not export donations.'); } }

  const nav: Array<[Tab,string]> = [['announcements','Announcements'],['members','People & roles'],['donations','Donations'],['settings','Mosque settings']];
  return <main className="min-h-screen" style={{ '--tenant-color': mosque?.brand_color || '#087f5b' } as React.CSSProperties}>
    <header className="tenant-band px-6 py-5 flex justify-between items-center"><div><p className="eyebrow">Tenant workspace / {slug}</p><h1 className="text-3xl font-bold">{mosque?.name || 'Mosque administration'}</h1></div><div className="flex gap-2"><Link href={`/mosque/${slug}/admin/analytics`} className="btn-secondary text-sm">View reports</Link><button className="btn-secondary text-sm" onClick={() => { clearToken(slug); router.push(`/mosque/${slug}`); }}>Sign out</button></div></header>
    <div className="max-w-6xl mx-auto px-6 py-10 grid md:grid-cols-[220px_1fr] gap-8">
      <nav className="space-y-2">{nav.map(([id,label]) => <button key={id} onClick={() => setTab(id)} className={tab === id ? 'btn-primary w-full' : 'btn-secondary w-full'}>{label}</button>)}</nav>
      <section>{error && <p className="mb-5 p-4 rounded-lg bg-red-50 text-red-700">{error}</p>}{message && <p className="mb-5 p-4 rounded-lg bg-emerald-50 text-emerald-800">{message}</p>}
        {tab === 'announcements' && <div className="space-y-6"><form onSubmit={publish} className="card-premium space-y-4"><p className="eyebrow">Public communication</p><h2 className="text-3xl font-bold">Publish an announcement</h2><input className="input-field" value={title} onChange={e => setTitle(e.target.value)} placeholder="Announcement title" required/><select className="input-field" value={category} onChange={e => setCategory(e.target.value)}><option>General</option><option>Event</option><option>Prayer</option><option>Urgent</option></select><textarea className="input-field min-h-28" value={content} onChange={e => setContent(e.target.value)} placeholder="What should the community know?" required/><button className="btn-primary">Publish announcement</button></form><div className="card-premium"><h2 className="text-2xl font-bold mb-5">Published noticeboard</h2>{announcements.map(a => <article key={a.announcement_id} className="py-4 border-b"><p className="eyebrow">{a.category}</p><h3 className="text-xl mt-2">{a.title}</h3><p className="text-slate-600 mt-1">{a.content}</p></article>)}</div></div>}
        {tab === 'members' && <div className="space-y-6"><form onSubmit={inviteMember} className="card-premium space-y-4"><p className="eyebrow">Access control</p><h2 className="text-3xl font-bold">Add a person</h2><div className="grid sm:grid-cols-2 gap-4"><input className="input-field" placeholder="Full name" value={invite.name} onChange={e => setInvite({...invite,name:e.target.value})} required/><input className="input-field" type="email" placeholder="Email" value={invite.email} onChange={e => setInvite({...invite,email:e.target.value})} required/><select className="input-field" value={invite.role} onChange={e => setInvite({...invite,role:e.target.value})}><option value="member">Member</option><option value="finance_officer">Finance officer</option><option value="programme_officer">Programme officer</option><option value="communications_officer">Communications officer</option><option value="tenant_admin">Tenant administrator</option></select><input className="input-field" type="password" minLength={8} placeholder="Temporary password" value={invite.temporary_password} onChange={e => setInvite({...invite,temporary_password:e.target.value})} required/></div><button className="btn-primary">Add person</button></form><div className="card-premium"><h2 className="text-2xl font-bold mb-5">People with access</h2>{members.map(m => <div key={m.membership_id} className="flex justify-between py-3 border-b"><span><strong>{m.user.name}</strong><small className="block text-slate-500">{m.user.email}</small></span><span className="text-sm">{m.role.replaceAll('_',' ')} · {m.status}</span></div>)}</div></div>}
        {tab === 'donations' && <div className="card-premium"><div className="flex justify-between mb-6"><div><p className="eyebrow">Financial records</p><h2 className="text-3xl font-bold">Donation ledger</h2></div><button onClick={exportDonations} className="btn-secondary text-sm">Export CSV</button></div>{donations.map(d => <div key={d.donation_id} className="grid grid-cols-4 gap-3 py-3 border-b text-sm"><strong>{d.receipt_number}</strong><span>{d.currency} {d.amount.toLocaleString()}</span><span>{d.category}</span><span>{d.reconciliation_status}</span></div>)}</div>}
        {tab === 'settings' && mosque && <form onSubmit={saveSettings} className="card-premium space-y-4"><p className="eyebrow">Tenant identity</p><h2 className="text-3xl font-bold">Mosque settings</h2><input className="input-field" value={mosque.name} onChange={e => setMosque({...mosque,name:e.target.value})}/><input className="input-field" value={mosque.address || ''} onChange={e => setMosque({...mosque,address:e.target.value})} placeholder="Address"/><div className="grid sm:grid-cols-2 gap-4"><input className="input-field" value={mosque.email || ''} onChange={e => setMosque({...mosque,email:e.target.value})} placeholder="Contact email"/><input className="input-field" value={mosque.phone || ''} onChange={e => setMosque({...mosque,phone:e.target.value})} placeholder="Phone"/><input className="input-field" value={mosque.timezone} onChange={e => setMosque({...mosque,timezone:e.target.value})} placeholder="Timezone"/><input className="input-field" type="color" value={mosque.brand_color} onChange={e => setMosque({...mosque,brand_color:e.target.value})}/></div><button className="btn-primary">Save settings</button></form>}
      </section>
    </div>
  </main>;
}
